# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2d18b2d8ad9ff640e0a32bfa7c538403"
application_url = "https://mt-even-employed-brooks.trycloudflare.com"
embedded = true
name = "dashboard"
handle = "dashboard-134"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mt-even-employed-brooks.trycloudflare.com/auth/callback",
  "https://mt-even-employed-brooks.trycloudflare.com/auth/shopify/callback",
  "https://mt-even-employed-brooks.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
